on:
  push:
    branches:
      - main

jobs:
  vpn-and-ssh-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          echo "$VPN_CONFIG" > /tmp/vpn_config.ovpn
          echo "hello world" > /tmp/temp.txt
          cat /tmp/vpn_config.ovpn
          cat /tmp/temp.txt
          ls /tmp
      - name: Connect to VPN
        # uses: "kota65535/github-openvpn-connect-action@v2"
        run: |
          pwd
          echo "hello"
          cat /tmp/vpn_config.ovpn
          echo "hello"
          ls /home/runner/work/mlops-project/mlops-project
        # with:
          # config_file: /tmp/vpn_config.ovpn
          # username: ${{ secrets.VPN_USERNAME }}
          # password: ${{ secrets.VPN_PASSWORD }}
